### ISSUE TITLE
Selecção de targets com lista de utilizadores

### ISSUE THREAD

**Issue by sdsantos** [vascopatricio/Gestor-Desktop#14]
E para definir os targets, não deveria ser inserir os IDs, porque ninguém sabe os IDs dos utilizadores. Deverás carregar a Team do Project seleccionado acima, e mostrar isso, numa lista em que dê para seleccionar múltiplos utilizadores.

**Comment by vascopatricio** [comment]
Já tá feito e funciona perfeitamente! Só falta aparecer a lista de users com eles seleccionados quando estamos a editar um ActionItem!

**Comment by vascopatricio** [comment]
Resolvido
