### ISSUE TITLE
Projecto não seleccionado ao editar action item

### ISSUE THREAD

**Issue by sdsantos** [vascopatricio/Gestor-Desktop#18]
Quando tento editar um action item, o projecto a que este pertence não é seleccionado.

**Comment by vascopatricio** [comment]
Testei no meu com dois casos diferentes e funciona sempre... podes especificar um pouco mais?

Se bem entendi, quando editas (clicas no título) de um ActionItem e aparece a janela de editar, na combobox que tem os projectos não aparece o projecto certo. É isso?

**Comment by sdsantos** [comment]
Yup, não aparece projecto nenhum seleccionado.
